[package]
name = "carbon-meteora-dlmm-decoder"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { path = "../../crates/core" }
serde = "1.0.136"
solana-sdk = "2.0.9"
async-trait = "0.1.82"
borsh = "1.5.1"
